---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-hub-1.20.0-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    nameOverride: artifact-hub
    hub:
      ingress:
        ingressClassName: kommander-traefik
        rules:
        - host: artifacthub.$(INGRESS_HOST).sslip.io
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: artifact-hub-hub
                    port:
                      number: 80
      service:
        type: ClusterIP
