---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ndk
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ndk
      sourceRef:
        kind: HelmRepository
        name: nutanix.github.io
        namespace: ${workspaceNamespace}
      version: 1.0.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: nutanix-ndk
  valuesFrom:
    - kind: ConfigMap
      name: ndk-1.0.0-defaults
  targetNamespace: ${releaseNamespace}
