---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: mongodb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnamicharts
        namespace: ${workspaceNamespace}
      version: 16.*
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: mongodb
  valuesFrom:
    - kind: ConfigMap
      name: mongodb-8.0.4-defaults
  targetNamespace: ${releaseNamespace}
