---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-storage
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: nutanix-csi-storage
      sourceRef:
        kind: HelmRepository
        name: nutanix.github.io
        namespace: ${workspaceNamespace}
      version: 2.6.6
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: csi-storage
  valuesFrom:
    - kind: ConfigMap
      name: csi-storage-2.6.6-defaults
  targetNamespace: ${releaseNamespace}
