---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: artifact-hub
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: artifact-hub
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: artifacthub.github.io
        namespace: ${workspaceNamespace}
      version: 1.20.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: artifact-hub
  valuesFrom:
    - kind: ConfigMap
      name: artifact-hub-1.20.0-defaults
  targetNamespace: ${releaseNamespace}
