---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnamicharts
  namespace: ${workspaceNamespace}
spec:
  url: "${helmMirrorURL:=oci://registry-1.docker.io/bitnamicharts}"
  interval: 10m
