---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm.coder.com
  namespace: ${workspaceNamespace}
  # labels:
  #   kommander.d2iq.io/dkp-airgapped: supported
spec:
  url: "${helmMirrorURL:=https://helm.coder.com/v2/}"
  interval: 10m
