---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cosi-driver
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: cosi-driver
      sourceRef:
        kind: HelmRepository
        name: nutanix.github.io
        namespace: ${workspaceNamespace}
      version: 0.0.4
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: cosi-driver
  valuesFrom:
    - kind: ConfigMap
      name: cosi-driver-0.0.4-defaults
  targetNamespace: ${releaseNamespace}
