---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ndb-operator
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ndb-operator
      sourceRef:
        kind: HelmRepository
        name: nutanix.github.io
        namespace: ${workspaceNamespace}
      version: 0.5.1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    remediation:
      retries: 30
  releaseName: nutanix-ndb-operator
  valuesFrom:
    - kind: ConfigMap
      name: ndb-operator-0.5.1-defaults
  targetNamespace: ${releaseNamespace}
